"""add messenger_handle to farmer

Revision ID: dc9af965fcf5
Revises: 04417280fb7b
Create Date: 2025-12-29 17:43:32.911691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9af965fcf5'
down_revision = '04417280fb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messenger_handle', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.drop_column('messenger_handle')

    # ### end Alembic commands ###
